name: Build Frontend

permissions:
  contents: write

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-frontend:
    uses: valdirsantos714/reusable_workflows/.github/workflows/build-nodejs.yaml@main
    with:
      working-directory: 'frontend'
      node-version: '20'
      push-image: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      docker-image-name: finance-manager-frontend
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}